"""email uniqued

Revision ID: a052bdda46b1
Revises: d7e185aad15d
Create Date: 2024-10-21 18:45:41.312600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a052bdda46b1'
down_revision: Union[str, None] = 'd7e185aad15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'checkthis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('checkthis', sa.VARCHAR(length=27), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
